### ISSUE TITLE
Question on Features and feature types

### ISSUE THREAD

**Issue by ngalbraith** [cf-convention/cf-conventions#196] opened 2019-08-07 17:19 UTC
I have a question about feature types and the timeseries_id attribute. This part of CF has never seemed clear to me, and I've been writing CF files for a really long time, so please bear with me if this all seems obvious to others!

We're working on 'long time series' datasets in the OceanSITES project. Most of our sites consist of surface moorings that are redeployed on some scheduled basis; we are going to present these deployments, concatenated in time, one file per site.  

The sites each have a nominal position, but the exact locations of the individual deployments vary slightly, because we like to have the old and new buoys overlap for a few days, for QC purposes, and we can't deploy a mooring on top of one that's already in the water. Other details also vary, like the models of the instruments used and, to some extent, their heights or depths (nominal heights are standard, but the actual height relative to the sea surface isn't known til after deployment, due to slight differences in load and/or buoyancy of the buoy).  Data from the overlap period is removed in the concatenated files; in some cases there are also gaps in time between deployments, due to instrument failures or buoys going adrift.

I'm structuring these files with a single time word; data variables have the single dimension TIME. The singleton LAT and LON contain the nominal site location. There is also a deployment dimension, used by variables like deployment_lat, deployment_lon. An extra variable deployment(TIME) is meant to be an index into the deployment variables, so if you need the exact sensor height for a point, you can find it in the deployment-dimensioned data.

My question is, can I give this data a featureType of timeseries, and should the deployment (dimension) variable have the cf_role 'timeseries_id'? Is this in fact a collection of timeseries, or a single timeseries? Is there a more standard way to tie the deployment-level data fields to the timeseries fields? Will any servers (thredds, errdap, etc) be able to understand how this data is structured?

Thanks - Nan Galbraith  (OBO OceanSITES data management team)

**Comment by dblodgett-usgs** [comment] 2019-08-09 12:19
Hi Nan, 

This is an interesting use case. I'll have to think about it a bit, but initial thought is you can have this one way or the other but not both. What I mean by that is you can have a single timeseries with a singleton `LAT`, `LON`, and `timeseries_id` _or_ you can have a collection of timeseries with your `deployment_lat`, `deployment_lon`, and `timeseries_id` (for the deployment). The idea of having a collection of timeseries intervals that form a single uber-timeseries isn't supported AFAIK.

- Dave

**Comment by ngalbraith** [comment] 2019-08-12 16:13
Thanks for the reply. Since the point of the long time series file is convenience for the user, I guess I'd have to go with the single time series. 

In that case, I'm not sure how I present the deployment-level data; but maybe that means this is no longer a question about feature types. Including deployment-dimensioned variables, without explicitly 'connecting' them to observational data seems less than ideal, and I'd love to get some suggestions on how this should be done. Maybe this isn't even a CF question at this point?

**Comment by dblodgett-usgs** [comment] 2019-08-13 02:19
Given that CF doesn't handle even well-structured multi-time series, such as forecast model run collections, I think this use case -- while fantastic -- is beyond the scope of CF, yes. Maybe someone else would have a different view though.

**Comment by graybeal** [comment] 2019-08-15 22:24
It might be a good use case for 'best practices' with CF, such as the example data sets that NOAA maintains. In my experience we generally would merge the original data into a new data product that was a single timeseries. My recollection of ways we've done this are that we either described the source of calculations in the file metadata—possibly without being precise about which variables came from which sources, yet ideally at least citing the software that defines that provenance precisely—or we created a variable array or comment for each variable that described the sources of each variable over time. 
  Under this scenario, unless the designer of the software that creates the merged timeseries makes the software track and records the exact provenance of the data, that provenance will be lost, and the product will be much less useful because of the lack of reproducibility.

**Comment by dblodgett-usgs** [comment] 2023-02-14 14:46
@ngalbraith -- can this question be closed out?

**Comment by larsbarring** [comment] 2023-12-21 15:19
Can this issue be closed with the acceptance of [discuss/#213](https://github.com/cf-convention/discuss/issues/213) standard names published in v82?

**Comment by JonathanGregory** [comment] 2023-12-28 21:07
As suggested by others, I believe this issue about deployment coordinates has now been solved with [new standard names](https://github.com/cf-convention/discuss/issues/213). I am therefore closing this issue. Please feel free to reopen it or start a new one, Nan @ngalbraith, if there are outstanding difficulties.

**Closed by JonathanGregory** 2023-12-28 21:07 UTC
Labels: question
