### ISSUE TITLE
Please improve description for direction_of_sea_water_velocity standard name

### ISSUE THREAD

**Issue by emontgomery-usgs** [cf-convention/cf-conventions#152] opened 2018-12-06 18:57 UTC
The description for the `direction_of_sea_water_velocity` standard name doesn't clearly state that it's a "to" direction. I assume it follows oceanographic convention, but think it needs to be stated explicitly.  Wind and wave direction variables have `_from` and` _to` options, with clear descriptions of what this means.  I think we can do better for `direction_of_sea_water_velocity`.
Thanks!

**Comment by ngalbraith** [comment] 2019-08-02 19:08
I don't see direction_of_sea_water_velocity in the current SN table, only sea_water_to_direction and sea_water_from_direction. Did this issue get reopened by accident?

**Comment by japamment** [comment] 2019-12-12 16:33
I am closing this issue because it refers to an alias of the current name sea_water_velocity_to_direction. The issue is resolved by the name change.

**Closed by japamment** 2019-12-12 16:33 UTC
Labels: standard name
